language: ruby
cache: bundler
rvm:
- 2.6.6
addons:
  postgresql: '9.6'
  sources:
  - google-chrome
  apt:
    packages:
    - google-chrome-stable
services:
  - redis-server
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo apt-get install libnss3
- sudo apt-get --only-upgrade install google-chrome-stable
- sudo cp chromedriver /usr/local/bin/.
- sudo chmod +x /usr/local/bin/chromedriver
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
 - RAILS_ENV=test bundle exec rails db:migrate --trace
 - bundle exec rails db:test:prepare
 - bundle exec rails test
 - bundle exec rails test:system
deploy:
  - provider: heroku
    api_key:
      secure: jheoABY2Yhe+eP4DB87h877u4cSc02Rf09PhmRxNroQQHv3XkToVgxXo33TEEuCoucDfhSepOeky4QozarJ7hSHCn1ssPb8jo3klicxPrB90t8SBPHB7evqfcaXAGYZBIPcvoGXzqQ0Brv/IvSP2eK81KUFAA8CAE9jUI4HXJkqRWnL2SC51yytxhnTBruOlTA3Z/90vgj9q6y3Y+xZCP3DrBDoBlvdaeyOXt54X+vcj+ZKepiMTdOuSEkC8dxuLiru7yMWZPANvvP/B/MLnh6XdG/EggRujR/uKvfrRKjKZjRt/TkMM7SarP+klGqOiaHV9KOct28E2Wbmoe03Qllk2NopqsanF4wemUWb8jCp4fLaf6e6KPnzA+Vfr3C8h1AyJYAXDXKx+jAa3pGDSSuDQmvO9lNtpLpxNbVwHSpBvdaY9MDta64oj+5eb2RR/UZZmB8JBuW2+2B22cf/OPU/Z915qWzshE3Fi0pTEgca4Tq37KqzyuYl8n4JnLxsUIWYVytWMMX8JtnvMYJdVLJEWrNidAD/BrZQGRhKUE8vnTMK7sFCzC2XInNpFXXDW0z2Keor8tb0Qk0y+PUyUlwy6YJgmITGkBHcRNWM0tYwO8+DS/duqvlSg0gMdxE6sa6mz9eVk1oP7KBJ/O4VdvJoRkdMiMKC9UvCceLqAT5A=
    app: sevaone
    on:
      repo: chaione/sevaone
    run:
      - "rails db:migrate"
      - "rails calculate_values"
      - "rake cleanup"
