default: &default
  categories:
    - groceries:
      - flour:
        - 5kg:
        - 10kg:
      - rice:
        - 1kg:
        - 2kg:
        - 5kg:
      - lentil:
        - 500g:
        - 1kg:
        - 2kg:
        - 5kg:
      - oil:
        - 500ml:
        - 1L:
        - 2L:
      - sugar:
        - 1kg:
        - 2kg:
        - 5kg:
      - tea_leaves:
        - 250g:
        - 500g:
        - 1kg:
      - potato:
        - 1kg:
        - 2kg:
        - 5kg:
      - onion:
        - 1kg:
        - 2kg:
        - 5kg:
      - milk_powder:
        - 200g:
        - 500g:
      - soap:
        - 1qty:
        - 2qty:
        - 5qty:
      - salt:
        - 1kg:
        - 2kg:
      - chilli_powder:
        - 200g:
      - turmeric:
        - 200g:
      - coriander_powder:
        - 200g:
      - garam_masala:
        - 200g:
  icons:
    groceries: cutlery
  en:
    categories: I need help with
    10kg: 10 kg
    1kg: 1 kg
    1L: 1 L
    1qty: 1 qty
    200g: 200 g
    250g: 250 g
    2kg: 2 kg
    2L: 2 L
    2qty: 2 qty
    500g: 500 g
    500ml: 500 ml
    5kg: 5 kg
    5qty: 5 qty
    chilli_powder: Red chilli powder
    coriander_powder: Dhaniya (Coriander) powder
    flour: Wheat flour
    garam_masala: Garam masala
    lentil: Lentil
    milk_powder: Milk powder
    oil: Edible oil
    onion: Onion
    potato: Potato
    rice: Rice
    salt: Salt
    soap: Soap
    sugar: Sugar
    tea_leaves: Tea leaves
    turmeric: Turmeric
    groceries: Groceries
  hi:
    # These keys need to be translated into Hindi
    categories: I need help with
    10kg: 10 kg
    1kg: 1 kg
    1L: 1 L
    1qty: 1 qty
    200g: 200 g
    250g: 250 g
    2kg: 2 kg
    2L: 2 L
    2qty: 2 qty
    500g: 500 g
    500ml: 500 ml
    5kg: 5 kg
    5qty: 5 qty
    chilli_powder: Red chilli powder
    coriander_powder: Dhaniya (Coriander) powder
    flour: Wheat flour
    garam_masala: Garam masala
    lentil: Lentil
    milk_powder: Milk powder
    oil: Edible oil
    onion: Onion
    potato: Potato
    rice: Rice
    salt: Salt
    soap: Soap
    sugar: Sugar
    tea_leaves: Tea leaves
    turmeric: Turmeric
    groceries: Groceries

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
