default: &default
  categories:
    - labor:
      - muck:
      - trash:
      - clean:
      - shop:
      - laundry:
      - cook:
      - sit:
      - medical:
    - equipment:
      - construction:
      - power_tools:
      - tools:
      - water_pump:
      - protective_gear:
      - generator:
      - dehumidifier:
      - appliances:
    - supplies:
      - construction:
      - home_repair:
      - cleaning_supplies:
      - household_items:
      - personal_care:
      - baby_and_child_care:
      - clothes:
      - medicine:
      - furniture:
      - fuel:
    - transportation:
      - pickup_truck:
      - bus_or_van:
      - tow_truck:
      - boat_motor:
      - boat_no_motor:
      - car:
    - housing:
      - family:
      - individual:
      - pets:
    - food:
      - ready_to_eat:
      - baby_formula:
      - drinking_water:
      - canned_food:
      - dry_foods:
      - basic_staples:
  icons:
    # Category keys that need icons will have their
    # corresponding icon key listed here
    labor: user-md
    equipment: wrench
    supplies: shopping-basket
    transportation: car
    housing: bed
    food: cutlery
  en:
    categories: Categories
    labor: Labor
    muck: Muck
    trash: Hauling Heavy Trash
    clean: Cleaning
    shop: Shopping
    laundry: Laundry
    cook: Cooking
    sit: Baby Sitting
    medical: Medical
    home_repair: Home Repair
    electrician: Electrician
    legal: Legal
    pest_control: Pest or Animal Control
    counselor: Counselor
    equipment: Equipment
    construction: Construction
    power_tools: Power Tools
    tools: Tools
    water_pump: Water Pumps
    protective_gear: Protective Gear
    generator: Generators
    dehumidifier: Dehumidifier
    appliances: Appliances
    other_equipment: Other Equipment
    supplies: Supplies
    cleaning_supplies: Cleaning Supplies
    household_items: Household Items
    personal_care: Personal Care
    baby_and_child_care: Baby & Child Care
    clothes: Clothes
    medicine: Medicine
    furniture: Furniture
    fuel: Fuel
    transportation: Transportation
    pickup_truck: Pickup Truck
    bus_or_van: Bus or Van
    tow_truck: Tow Truck
    boat_motor: Boat (motor)
    boat_no_motor: Boat (no motor)
    car: Car
    housing: Housing
    family: Family
    individual: Individual
    pets: Pets
    food: Food
    ready_to_eat: Ready to Eat
    baby_formula: Baby Formula
    drinking_water: Drinking Water
    canned_food: Canned Food
    dry_foods: Dry Foods
    basic_staples: Basic Staples
  es:
    categories: Categories
    labor: Labor
    muck: Muck
    trash: Hauling Heavy Trash
    clean: Cleaning
    shop: Shopping
    laundry: Laundry
    cook: Cooking
    sit: Baby Sitting
    medical: Medical
    home_repair: Home Repair
    electrician: Electrician
    legal: Legal
    pest_control: Pest or Animal Control
    counselor: Counselor
    equipment: Equipment
    construction: Construction
    power_tools: Power Tools
    tools: Tools
    water_pump: Water Pumps
    protective_gear: Protective Gear
    generator: Generators
    dehumidifier: Dehumidifier
    appliances: Appliances
    supplies: Supplies
    cleaning_supplies: Cleaning Supplies
    household_items: Household Items
    personal_care: Personal Care
    baby_and_child_care: Baby & Child Care
    clothes: Clothes
    medicine: Medicine
    furniture: Furniture
    fuel: Fuel
    transportation: Transportation
    pickup_truck: Pickup Truck
    bus_or_van: Bus or Van
    tow_truck: Tow Truck
    boat_motor: Boat (motor)
    boat_no_motor: Boat (no motor)
    car: Car
    housing: Housing
    family: Family
    individual: Individual
    pets: Pets
    food: Food
    ready_to_eat: Ready to Eat
    baby_formula: Baby Formula
    drinking_water: Drinking Water
    canned_food: Canned Food
    dry_foods: Dry Foods
    basic_staples: Basic Staples

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default